# -*- coding: utf-8 -*-
"""PRIMER PARCIAL ESTRUCTURAS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XyUR8aJvrOx0googIjriogCD3fJHveez
"""

#Primer parcial
from time import time
import random

def burbuja(v):
  for i in range(1,len(v)):
    for j in range(0,len(v)-i):
      if(v[j+1] > v[j]):
        aux=v[j];
        v[j]=v[j+1];
        v[j+1]=aux;

n=int(input("digite la cantidad de registros a utilizar: "))
v=[]
t=time()
for i in range(0,n):
    n1  = random.randint(1,100)
    n2 = random.randint(1,100)
    n3 = random.randint(1,100)

    mayor=n1
    if mayor<n2:
        mayor=n2
    if mayor<n3:
        mayor=n3
    else:
        suma=(n1+n2+n3)-mayor
        v.append(suma)
        
burbuja(v)

print("Vector: ",v)
print("Tres numeros mas grandes: ",v[0],",",v[1],",",v[2])      
print(time()-t)

#Segundo punto
def potencia(A,n):
    if n==0:
        return 1
    else:
        return A*potencia(A,n-1)

A=int(input("Digite numero: "))
n=int(input("Digite potencia: "))
limite=int(A//2)

for i in range(limite):
    base=potencia(A,n)

print(base)